[package]
name = "sc2-prost"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
prost = "0.14"
serde = { version = "1.0", features = ["derive"], optional = true }
glam = { version = "0.30", optional = true }

[build-dependencies]
prost-build = "0.14"
